id: IAA05B369
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T16:54:00+00:00'
last_modified: '2022-06-07T20:26:34.713182+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2122
  title: གསུང་འབུམ། དཀོན་མཆོག་འཇིགས་མེད་དབང་པོ ༼བླ་བྲང་པར་མ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    DB82:
      image_group_id: I5259
      title: ''
      total_pages: 570
      order: 1
      base_file: DB82.txt
    3A3C:
      image_group_id: I5260
      title: ''
      total_pages: 708
      order: 2
      base_file: 3A3C.txt
    E148:
      image_group_id: I5261
      title: ''
      total_pages: 720
      order: 3
      base_file: E148.txt
    778F:
      image_group_id: I5262
      title: ''
      total_pages: 586
      order: 4
      base_file: 778F.txt
    BFC4:
      image_group_id: I5263
      title: ''
      total_pages: 728
      order: 5
      base_file: BFC4.txt
    175F:
      image_group_id: I5264
      title: ''
      total_pages: 726
      order: 6
      base_file: 175F.txt
    2B26:
      image_group_id: I5265
      title: ''
      total_pages: 762
      order: 7
      base_file: 2B26.txt
    '4955':
      image_group_id: I5266
      title: ''
      total_pages: 796
      order: 8
      base_file: 4955.txt
    60AA:
      image_group_id: I5267
      title: ''
      total_pages: 914
      order: 9
      base_file: 60AA.txt
    ACA3:
      image_group_id: I5268
      title: ''
      total_pages: 880
      order: 10
      base_file: ACA3.txt
    '9718':
      image_group_id: I5269
      title: ''
      total_pages: 568
      order: 11
      base_file: 9718.txt
    414F:
      image_group_id: I5270
      title: ''
      total_pages: 492
      order: 12
      base_file: 414F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
